### ISSUE TITLE
Version 0.0.19 depth is not defined

### ISSUE THREAD

**Issue by ablesea** [resendlabs/react-email#1074]
### Describe the Bug

When running 
```
# Version 0.0.19
npx create-email@latest
```

Some files are moved before the script throws an error 
```
file:///C:/Users/xxxxxx/AppData/Local/npm-cache/_npx/5e64a2f331305744/node_modules/create-email/src/index.js:31
    l: depth,
       ^

ReferenceError: depth is not defined
    at Command.init (file:///C:/Users/ablesea/AppData/Local/npm-cache/_npx/5e64a2f331305744/node_modules/create-email/src/index.js:31:8)
    at Command.listener [as _actionHandler] (C:\Users\ablesea\AppData\Local\npm-cache\_npx\5e64a2f331305744\node_modules\commander\lib\command.js:482:17)
    at C:\Users\ablesea\AppData\Local\npm-cache\_npx\5e64a2f331305744\node_modules\commander\lib\command.js:1264:65
    at Command._chainOrCall (C:\Users\ablesea\AppData\Local\npm-cache\_npx\5e64a2f331305744\node_modules\commander\lib\command.js:1158:12)
    at Command._parseCommand (C:\Users\ablesea\AppData\Local\npm-cache\_npx\5e64a2f331305744\node_modules\commander\lib\command.js:1264:27)
    at Command.parse (C:\Users\ablesea\AppData\Local\npm-cache\_npx\5e64a2f331305744\node_modules\commander\lib\command.js:890:10)
    at file:///C:/Users/ablesea/AppData/Local/npm-cache/_npx/5e64a2f331305744/node_modules/create-email/src/index.js:49:4
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

This seems to be a problem with version 0.0.19 downgrading to 0.0.18 will allow you to run the script.

### Which package is affected (leave empty if unsure)

create-email

### Link to the code that reproduces this issue

https://localhost:3000

### To Reproduce

Run the create script

```bash
npx create-email@latest 
```

### Expected Behavior

Should initialize the project without error.

### What's your node version? (if relevant)

20.10

**Comment by gabrielmfern** [comment]
This has been solved on main we are just needing to publish the new version for it, but this is a known issue, sadly for now you'll have to use the bit older less stable version :(

**Comment by pepsiamir** [comment]
I have the same problem, please publish it soon

**Comment by SanderCokart** [comment]
Same issue here

**Comment by john-griffin** [comment]
Same here

**Comment by johanguse** [comment]
+ 1

**Comment by johanguse** [comment]
Yes, it does not work with 0.0.19

**Comment by gabrielmfern** [comment]
Hey, guys sorry for taking too long on publishing this, it should now be fixed and running `npx create-email@latest` should work without any problems.

https://react.email/docs/changelog#dec-11-2023
