### ISSUE TITLE
Upgrading from version 1.1.1 to 1.6.1 fails at runtime

### ISSUE THREAD

**Issue by harshav17** [resendlabs/react-email#334]
Hello Team,

I started using react-email 1.1.1 to generate a couple of emails. Wanted to upgrade to latest and greatest. After upgrading and running `yarn dev`, I get the following error.

```
$ email dev
verbose 0.4154785 Error: Command failed with exit code 1.
    at ProcessTermError.ExtendableBuiltin (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:750:123)
    at new ProcessTermError (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:790:113)
    at /opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:34406:30
    at Generator.throw (<anonymous>)
    at step (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:310:30)
    at /opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I am using node v19.4.0 and yarn 1.22.19. And my package.json has the following...

```
    "@react-email/button": "^0.0.5",
    "@react-email/container": "^0.0.5",
    "@react-email/head": "^0.0.3",
    "@react-email/heading": "^0.0.6",
    "@react-email/hr": "^0.0.3",
    "@react-email/html": "^0.0.3",
    "@react-email/img": "^0.0.3",
    "@react-email/link": "^0.0.3",
    "@react-email/preview": "^0.0.3",
    "@react-email/section": "^0.0.4",
    "@react-email/text": "^0.0.3",
    "react-email": "^1.6.1"
```

Any pointers on what's going on here?

**Comment by bukinoshita** [comment]
Are you running in an existing emails folder that you had before?

**Comment by harshav17** [comment]
Correct. To mention though, this project I created stands by itself and there is no other code/components other than what react-email documentation suggested.

**Comment by bukinoshita** [comment]
Does removing `.react-email` folder and re-running `email dev` works?

**Comment by zenorocha** [comment]
Closing due to inactivity.
