### ISSUE TITLE
sendgrid - npm run dev - Error: Element type is invalid - You likely forgot to export your component 

### ISSUE THREAD

**Issue by martijnvandenboom** [resendlabs/react-email#426]
Dear reader,

In an attempt to make a typescript web app that will send an email I have tried following steps:

1. % npx create-remix@latest 
2. cd into the directory of your newly created app folder
3. % npm install @react-email/html @react-email/button @react-email/render @sendgrid/mail
4. I copied the contents of the index.tsx to the root.tsx
5. and I created the email.tsx
6. I put the SENDGRID_API_KEY in the .env file
7. % npm run dev

Then I go to the web browser address: localhost:3000
And I get the error below.

Do you know how to resolve this?

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at renderElement (/Users/<user>/Documents/webapps/typescript/typescript-test-0002/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6047:9)
    at renderNodeDestructiveImpl (/Users/<user>/Documents/webapps/typescript/typescript-test-0002/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/Users/<user>/Documents/webapps/typescript/typescript-test-0002/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at retryTask (/Users/<user>/Documents/webapps/typescript/typescript-test-0002/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6532:5)
    at performWork (/Users/<user>/Documents/webapps/typescript/typescript-test-0002/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6580:7)
    at /Users/<user>/Documents/webapps/typescript/typescript-test-0002/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6904:12
    at scheduleWork (/Users/<user>/Documents/webapps/typescript/typescript-test-0002/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:78:3)
    at startWork (/Users/<user>/Documents/webapps/typescript/typescript-test-0002/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6903:3)
    at renderToStringImpl (/Users/<user>/Documents/webapps/typescript/typescript-test-0002/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6977:3)
    at Object.renderToStaticMarkup (/Users/<user>/Documents/webapps/typescript/typescript-test-0002/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:7069:10)

Sincerely

**Comment by bukinoshita** [comment]
Can you share the `email.tsx` code?

**Comment by martijnvandenboom** [comment]
Hello Bu,

See the attachment.

Sincerely,
Martijn
