### ISSUE TITLE
Tailwind is throwing an error in production (not dev)

### ISSUE THREAD

**Issue by matt-aitken** [resendlabs/react-email#506]
Given the following simple email:

```ts
<Html>
    <Head />
    <Tailwind>
      <Button className="bg-slate-900 text-slate-900">Test</Button>
    </Tailwind>
  </Html>
```

When run in production the following error is thrown:

```
TypeError: e.replaceAll is not a function
    at dp (/opt/render/project/src/node_modules/tw-to-css/dist/index.js:41:516)
    at /opt/render/project/src/node_modules/tw-to-css/dist/index.js:41:406
    at Array.map (<anonymous>)
    at dp (/opt/render/project/src/node_modules/tw-to-css/dist/index.js:41:399)
    at /opt/render/project/src/node_modules/tw-to-css/dist/index.js:41:567
    at /opt/render/project/src/node_modules/tw-to-css/dist/index.js:41:779
    at replaceTailwindStyles (/opt/render/project/src/node_modules/@react-email/tailwind/dist/index.js:50:41)
    at /opt/render/project/src/node_modules/react/cjs/react.production.min.js:18:85
    at R (/opt/render/project/src/node_modules/react/cjs/react.production.min.js:16:230)
    at Object.S [as map] (/opt/render/project/src/node_modules/react/cjs/react.production.min.js:18:52)
```

It looks like `classList` on this line of `tw-to-css` is undefined/null: https://github.com/vinicoder/tw-to-css/blob/c98d9b009c4cec298846eed4bb53f976675d5197/src/index.ts#L43

Note that this doesn't happen in development, only production.

**Comment by bukinoshita** [comment]
Going to open that on `tw-to-css` package.

**Comment by bukinoshita** [comment]
We can follow on https://github.com/vinicoder/tw-to-css/issues/2
