### ISSUE TITLE
Preview Mode breaks when importing any files outside of the emails/ directory

### ISSUE THREAD

**Issue by EyMaddis** [resendlabs/react-email#613]
### Describe the Bug

When importing any file inside any `emails/*.tsx` file that is not from within the `emails` directory, the preview mode crashes because it cannot find the file.

In my reproduction example I created `some-file.ts` at the root of my project and imported it within `emails/index.tsx`.
```tsx
import { Button } from '@react-email/button';
import { Html } from '@react-email/html';
import * as React from 'react';

// THIS DOES NOT LOAD IN PREVIEW MODE
import { someValue } from '../someFile';

export default function Email() {
  return (
    <Html>
      <Button
        pX={20}
        pY={12}
        href="https://example.com"
        style={{ background: '#000', color: '#fff' }}
      >
        {someValue}
      </Button>
    </Html>
  );
}
```

![image](https://user-images.githubusercontent.com/1409100/229307247-89b96363-a9cb-41e4-887e-c792aad047fb.png)

```
npm run email:dev -- --port 6005

> react-email-import-bug@0.1.0 email:dev
> email dev "--port" "6005"

⠋ Generating emails previewcp: no such file or directory: static
cat: no paths given
{
  error: Error: Something went wrong while copying the file to /react-email-import-bug/emails/static, 
      at createStaticFiles (/react-email-import-bug/node_modules/react-email/dist/source/utils/generate-email-preview.js:47:15)
      at async generateEmailsPreview (/react-email-import-bug/node_modules/react-email/dist/source/utils/generate-email-preview.js:18:9)
      at async setupServer (/react-email-import-bug/node_modules/react-email/dist/source/utils/run-server.js:30:9)
      at async Command.dev (/react-email-import-bug/node_modules/react-email/dist/source/commands/dev.js:17:13)
}
⠋ Installing dependencies...

up to date, audited 545 packages in 694ms

141 packages are looking for funding
  run `npm fund` for details

✔ Dependencies installed
⠹ Generating emails preview
> react-email-client@0.0.11 dev
> next dev "-p" "6005"

⠦ Generating emails previewready - started server on 0.0.0.0:6005, url: http://localhost:6005
⠧ Generating emails previewwarn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
warning package.json: "dependencies" has dependency "@types/node" with range "18.15.11" that collides with a dependency in "devDependencies" of the same name with version "18.11.9"
warning package.json: "dependencies" has dependency "@types/react" with range "18.0.31" that collides with a dependency in "devDependencies" of the same name with version "18.0.25"
warning package.json: "dependencies" has dependency "@types/react-dom" with range "18.0.11" that collides with a dependency in "devDependencies" of the same name with version "18.0.9"
warning package.json: "dependencies" has dependency "typescript" with range "5.0.3" that collides with a dependency in "devDependencies" of the same name with version "4.9.3"
warning ../../package.json: No license field
⠏ Generating emails previewevent - compiled client and server successfully in 657 ms (262 modules)
⠹ Generating emails previewwait  - compiling...
⠸ Generating emails previewevent - compiled client and server successfully in 144 ms (262 modules)
⠼ Generating emails previewwait  - compiling /preview/[slug]/page (client and server)...
⠧ Generating emails previewerror - ./emails/index.tsx:4:0
Module not found: Can't resolve '../someFile'
  2 | import { Html } from '@react-email/html';
  3 | import * as React from 'react';
> 4 | import { someValue } from '../someFile';
  5 | 
  6 | export default function Email() {
  7 |   return (

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./emails/ lazy ^\.\/.*$ namespace object
./src/app/preview/[slug]/page.tsx
⠇ Generating emails previewwait  - compiling...
⠏ Generating emails previewevent - compiled successfully in 152 ms (745 modules)
⠼ Generating emails previewwait  - compiling /_error (client and server)...
⠼ Generating emails previewerror - ./emails/index.tsx:4:0
Module not found: Can't resolve '../someFile'
  2 | import { Html } from '@react-email/html';
  3 | import * as React from 'react';
> 4 | import { someValue } from '../someFile';
  5 | 
  6 | export default function Email() {
  7 |   return (

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./emails/ lazy ^\.\/.*$ namespace object
./src/app/preview/[slug]/page.tsx
⠦ Generating emails preview
```

Also note that the process always throws an error `Generating emails previewcp: no such file or directory: static
cat: no paths given`. However, this seems to not have an impact once the `emails/static` folder exists.

## Why is this important

I generally want to reuse code in mails from the main project, like types or the `tailwind.configs.js` file.

## Why is this happening
The preview mode seems to use Next.js and copies all `emails/*` files to `.react-email/emails` which changes the import paths. This would require an import like `../some-file.js` for the regular project and `../../some-file.js` for the preview mode.

### Link to the code that reproduces this issue

https://EyMaddis@github.com/EyMaddis/react-email-import-bug.git

### To Reproduce

* clone the repo
* run `npm install`
* run `npm run dev`
* open http://localhost:3000
* observe the "Hello World" on the index page ✅ 

Start the preview mode
* run `npm run email:dev -- --port 6005` (port is irrelevant here)
* open http://localhost:6005 
* observe the described error.

### Expected Behavior

Preview mode should compile and show "Hello World", same as the Next.js App

**Comment by kafkas** [comment]
+1. Having the same issue.

**Comment by EyMaddis** [comment]
I prepared a PR: https://github.com/resendlabs/react-email/pull/615 😊

**Comment by kleenkanteen** [comment]
This is still an issue on windows 10...

**Comment by kleenkanteen** [comment]
Downgrading react-email in rallly/packages/emails/package.json to [1.7.15](https://www.npmjs.com/package/react-email/v/1.7.15) resolves the error.
