### ISSUE TITLE
Manual setup does not work

### ISSUE THREAD

**Issue by yannxaver** [resendlabs/react-email#651]
### Describe the Bug

https://react.email/docs/getting-started/manual-setup

1. Does not install `React` as a dependency in Step 2 even though it gets imported in Step 4
2. The dev server gets stuck in an endless loop

```
> email dev

⠋ Generating emails previewcp: no such file or directory: static
cat: no paths given
{
  error: Error: Something went wrong while copying the file to /Users/foo/Documents/Apps/chat/packages/email/emails/static,
      at createStaticFiles (/Users/foo/Documents/Apps/chat/node_modules/.pnpm/react-email@1.9.1/node_modules/react-email/dist/source/utils/generate-email-preview.js:47:15)
      at async generateEmailsPreview (/Users/foo/Documents/Apps/chat/node_modules/.pnpm/react-email@1.9.1/node_modules/react-email/dist/source/utils/generate-email-preview.js:18:9)
      at async setupServer (/Users/foo/Documents/Apps/chat/node_modules/.pnpm/react-email@1.9.1/node_modules/react-email/dist/source/utils/run-server.js:30:9)
      at async Command.dev (/Users/foo/Documents/Apps/chat/node_modules/.pnpm/react-email@1.9.1/node_modules/react-email/dist/source/commands/dev.js:21:9)
}
⠋ Installing dependencies...
Scope: all 7 workspace projects
✔ Dependencies installed
⠸ Generating emails preview
> react-email-client@0.0.12 dev /Users/foo/Documents/Apps/chat/packages/email/.react-email
> next dev "--" "-p" "3000"

sh: next: command not found
 ELIFECYCLE  Command failed.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
⠴ Generating emails preview
```

### Which package is affected (leave empty if unsure)

docs

### Link to the code that reproduces this issue

https://react.email/docs/getting-started/manual-setup

### To Reproduce

Follow the manual setup guide

### Expected Behavior

Start the dev server correctly

**Comment by arvindell** [comment]
I'm experiencing the same issue

**Comment by brunowego** [comment]
If you are using `pnpm` with `turborepo`, try add `./packages/mailer/.react-email` to `pnpm-workspace.yaml`:

```yml
---
packages:
  - ./apps/*
  - ./packages/*
  - ./packages/mailer/.react-email
```

**Comment by bukinoshita** [comment]
This is probably the same issue as https://github.com/resendlabs/react-email/issues/656
